### ISSUE TITLE
Créer une classe de gestion des appels REST

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-android#11]
- URGENT

**Comment by CrisCR** [comment]
Commit push avec pas mal de changements.
Comme il était convenu j'ai rassembler les différentes interfaces pour n'en faire que deux:
-RestUserInterface: avec inscription,login, get profil et set profil
-RestEventInterface: avec insciption, get event et set event
La création d'une interface se fait désormais beaucoup plus dynamiquement, avec 2 lignes de code pour initialiser une interface quand il en fallait 20 avant.

Après ça j'ai fais un gros nettoyage du code pour mieux s'y retrouver, avec la suppression des classes qui n'étaient pas utilisées et le changement des noms des packages qui sont maintenant plus explicite qu'avant.

**Comment by serkansahin** [comment]
Génial Chris :) ! On va pouvoir y aller très vite maintenant.
