### ISSUE TITLE
Vue Home - Developpement

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-android#2]
- Utiliser le Material Design de Google
- Compatibilité Android 5.1!

Root: https://github.com/Aeradriel/birdl/issues/63

**Comment by serkansahin** [comment]
On a quoi au niveau du design ? possibilité que tu implémentes des éléments en durs en attendant de dynamiser ?

**Comment by serkansahin** [comment]
On a quoi au niveau du design ? possibilité que tu implémentes des éléments en dur en attendant de dynamiser ?

**Comment by serkansahin** [comment]
Pour la mise à jour des infos users, le code semble me dire que c'est good alors que ça ne l'est pas. Pourtant j'avais réussi à faire fonctionner avec le mdp en dur dans le code...Je débug ça, est-ce qu'il y a un autre point à dynamiser sur lequel je peux travailler ? @CrisCR

**Comment by serkansahin** [comment]
@CrisCR Du nouveau ? N'hésites pas me contacter pour voir sur quoi on pourrait se pencher.

**Comment by CrisCR** [comment]
Alors il y a:
- la trad de l'appli à faire
- la gestion des messages (envoie et réception)
- la page d’accueil avec le niveau d'anglais + le HOF.
  Créer toi un ticket sur ce que tu veux faire.

**Comment by serkansahin** [comment]
Dac, je suis sur la connexion avec Google pour l'instant mais je vais m'assigner l'une de ces 3 tâches. T'as pu finir pour la gestion des events ?

**Comment by CrisCR** [comment]
Tout est en place mais les appels à l'API ne marchent pas, faut que je vois ça avec thibaut soit se soir soit demain.

**Comment by serkansahin** [comment]
Ok je ferme ce ticket ! Tu as le ticket "Dynamiser les events" pour ça ;).
