### ISSUE TITLE
Général - Header Information Catcher (HIC)

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-android#4]
Récupérer l'access-token contenu dans le header de réponse à la connexion de l'utilisateur (process login).

Login process (email:password) -> API
API response (access-token -> 201 Created) -> HIC.

Cela permettra de dynamiser toute l'application.

**Comment by CrisCR** [comment]
L'access-token est récupéré et j'arrive à faire des opérations sur l'api (récupérer les infos user, etc).
Demain je m'occupe de rendre l'apli dynamique.

**Comment by serkansahin** [comment]
Et bah voilà je savais que tu le pouvais :3 ! Je peux fermer le ticket !
