### ISSUE TITLE
Dynamiser la messagerie

### ISSUE THREAD

**Issue by serkansahin** [Aeradriel/birdl-android#7]
Pouvoir envoyer et recevoir des messages

**Comment by serkansahin** [comment]
J'attends toutes les clés + values des routes de la part de Thibaut.

**Comment by serkansahin** [comment]
messages/new  : sender_id (id de l'envoyeur), receiver_id (id du receveur), content (contenu message) (POST)
messages : relation (id d'une relation) (GET)
messages/sent : pas de paramètre (GET)
messages/received : pas de paramètre (GET)
messages/relations : donne la liste des ids des contacts (GET)

**Comment by CrisCR** [comment]
L'interface de messagerie à été ajouté dans le package "RetrofitInterface" sous le nom "RestMessageInterface".
Pour l'utiliser il faut initialer une nouvelle instance de la classe BirdlConfigNetwork, qui va s'occuper d'initialer le rest adapter ainsi que toutes les merdes qui vont avec.
Ensuite tu initialise une nouvelle interface Rest avec la classe RestInterface en mettant en paramètre une instance de BirddConfigNetwork et le mot clé "message".

BirdlConfigNetwork messageNetwork = new BirdlConfigNetwork();
RestInterface restMessage = new RestInterface(messageNetwork, "message");

Après t’appelles juste ta méthode de l'interface comme suit:
restMessage.getMessageInterface().getMessage(new Callback<AllEventResponse>()
                     ~~                                 .getMessageSent(new Callback<AllEventResponse>()
                                                         etc.

Sinon t'as un bon tuto dans le tab1.java ou le Login.java.

**Comment by serkansahin** [comment]
tkt je prends note merci !

**Comment by serkansahin** [comment]
Re alors je sais pas ce qu'il se passe mais quand je déclare tes classes BirdlConfigNetwork & RestInterface ils apparaissent en rouge :/ ! j'ai mis dans les includes import config.BirdlConfigNetwork; & import config.RestInterface; et ça met le mot "config" en rouge.

Du coup je ne peux pas vraiment tester mon code, j'ai vérifier tab1.java et Login.java et là encore j'ai des classes non reconnues.

Je précise que j'ai recloné le projet sur une installation d'Android Studio propre et fonctionnelle (testée avec l'émulateur).

@CrisCR 

UPDATE: effectivement toutes les classes sous le dossier "Config" ne sont pas reconnues.

![login](https://cloud.githubusercontent.com/assets/9954851/11711776/12b6aa00-9f29-11e5-8171-e0ad4590df36.png)
![mesage](https://cloud.githubusercontent.com/assets/9954851/11711775/12b32b28-9f29-11e5-8416-07cd2d2ec1b4.png)

**Comment by serkansahin** [comment]
La query rest fonctionne correctement, je m'attaque à l'affichage des messages

**Comment by serkansahin** [comment]
Fini
